//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigator.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Kandidat : INotifyPropertyChanged
    {
        private decimal jMBG;
        private string ime;
        private string prezime;
        private DateTime godinaRodjenja;
        private string email;
        private string telefon;
        private string napomena;
        private bool zaposlen;
        private DateTime datumPoslednjeIzmene;

        public decimal JMBG
        {
            get => jMBG; set
            {
                jMBG = value;
                OnPropertyChanged(nameof(JMBG));
            }

        }
        public string Ime {
            get => ime; set
            {
                ime = value;
                OnPropertyChanged(nameof(Ime));
            }
        }
        public string Prezime {
            get => prezime; set
            {
                prezime = value;
                OnPropertyChanged(nameof(Prezime));
            }
        }
        public System.DateTime GodinaRodjenja {
            get => godinaRodjenja; set
            {
                godinaRodjenja = value;
                OnPropertyChanged(nameof(GodinaRodjenja));
            }
        }
        public string Email {
            get => email; set
            {
                email = value;
                OnPropertyChanged(nameof(Email));
            }
        }
        public string Telefon {
            get => telefon; set
            {
                telefon = value;
                OnPropertyChanged(nameof(Telefon));
            }
        }
        public string Napomena {
            get => napomena; set
            {
                napomena = value;
                OnPropertyChanged(nameof(Napomena));
            }
        }
        public bool Zaposlen {
            get => zaposlen; set
            {
                zaposlen = value;
                OnPropertyChanged(nameof(Zaposlen));
            }
        }
        public System.DateTime DatumPoslednjeIzmene {
            get => datumPoslednjeIzmene; set
            {
                datumPoslednjeIzmene = value;
                OnPropertyChanged(nameof(DatumPoslednjeIzmene));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
